### ISSUE TITLE
Remove "async" version

### ISSUE THREAD

**Issue by fresheneesz** [Sembiance/email-validator#18]
The async version is a worse API and not asynchronous in any way. It should be removed to simplify the API and make the package smaller.

**Comment by fresheneesz** [comment]
https://github.com/Sembiance/email-validator/pull/19

**Comment by adboul** [comment]
I agree, you may use setTimeout(() => exporter.validate(email), 0) to actually make it async but I really don't see the need here as it is basically just a regex validation.

**Comment by kartsims** [comment]
Agree, this PR should be merged

**Comment by dthree** [comment]
Agreed. I suspected the package did an online check or something and had to look at the source code because I was confused. There's really no point to this.
