### ISSUE TITLE
Add callback support

### ISSUE THREAD

**Issue by zhe13** [Sembiance/email-validator#7]
well .I have already installed email-validator from npm and it's version is 1.0.3.
I just follow the instruction requiring module and using the "validate" function to my mail-address.
Nothing happens.
=-=Maybe you can change the api to something like e.validate("test@test.com",function(err,res){...}); for debugging?

**Comment by Sembiance** [comment]
Right now that function is synchronous and just returns true or false depending on whether it passed or failed validation.

I'll look into adding a callback version as you suggested.

**Comment by argonlaser** [comment]
Hi, I have added a pull request to address the issue. Please have a look at it and provide comments.

**Comment by argonlaser** [comment]
https://github.com/Sembiance/email-validator/pull/12 is the PR that could address the issue.

**Comment by Sembiance** [comment]
I merged PR #12 so this issue is now complete.

**Comment by fresheneesz** [comment]
@Sembiance Why was the async version added? First of all its not asynchronous, and second of all @zhe13 should have just wrapped the synchronous function himself if he didn't want to refactor his own code. This change wasn't reasonable.
